version: "3.8"

services:
  app:
    container_name: app
    build: .
    image: fiber-gorm-microservice
    environment:
      - MYSQL_URL=sql://user:pass
      - MONGODB_URL=mongodb://mongodb:27017/go-boilerplate
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysqldb
    networks:
      - go-network

  mysqldb:
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'boilerplate_go'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_HOST: "%" # Allow connections from outside the container
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./docker/scripts/schema.sql:/docker-entrypoint-initdb.d/setup.sql
      - dbdata:/var/lib/mysql
    networks:
      - go-network
volumes:
  dbdata:

networks:
  go-network:
    driver: bridge